export const TECH_TAGS = [
  "< />",
  "HTML",
  "CSS",
  "JS",
  "TypeScript",
  "TS",
  "React",
  "Next.js",
  "Tailwind",
  "Node.js",
  "Vite",
  "SEO",
  "UX",
  "API",
  "REST",
  "JWT",
  "SSR",
  "ISR",
  "SPA",
  "PWA",
  "Zod",
  "Prisma",
  "Express",
  "Router",
  "WordPress",
  "Elementor",
  "WooCommerce",
  "ACF",
  "Divi",
  "GA4",
  "GTM",
  "GSC",
  "Schema",
  "Sitemap",
] as const;

export const COLOR_BY_TECH: Record<string, string> = {
  "< />": "text-zinc-300",
  HTML: "text-orange-400",
  CSS: "text-sky-400",
  JS: "text-yellow-400",
  TypeScript: "text-blue-400",
  TS: "text-blue-400",
  React: "text-cyan-400",
  "Next.js": "text-zinc-300",
  Tailwind: "text-teal-400",
  "Node.js": "text-emerald-400",
  Vite: "text-fuchsia-400",
  SEO: "text-amber-300",
  UX: "text-pink-300",
  API: "text-indigo-300",
  REST: "text-indigo-300",
  JWT: "text-purple-300",
  Zod: "text-green-300",
  Prisma: "text-emerald-300",
  Express: "text-neutral-300",
  Router: "text-purple-300",
  SSR: "text-slate-300",
  ISR: "text-slate-300",
  SPA: "text-slate-300",
  PWA: "text-violet-300",
  WordPress: "text-blue-300",
  Elementor: "text-rose-300",
  WooCommerce: "text-fuchsia-300",
  ACF: "text-lime-300",
  Divi: "text-purple-300",
  GA4: "text-emerald-300",
  GTM: "text-cyan-300",
  GSC: "text-amber-300",
  Schema: "text-green-300",
  Sitemap: "text-sky-300",
};

export const SIZE_CLASSES = [
  "text-[12px]",
  "text-[14px]",
  "text-[16px]",
  "text-[18px]",
  "text-[20px]",
] as const;
